[package]
name = "world-block-macros"
version = "0.0.0"
edition = "2021"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
heck = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

[lints]
workspace = true
